### ISSUE TITLE
From header in emails

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2DROP/b2drop-theme#24]
Notification emails sent from production system has `From: b2drop <b2drop@b2drop.fz-juelich.de>`. This should preferably be changed to a combination of the below:

1. Set e.g `From: EUDAT B2DROP <no-reply@b2drop.eudat.eu>`, if we don't want replies to the source emails
2. Add a `Reply-to` header with Helpdesk email and queue, for replies
3. Contain information about questions and replies plus a link to https://www.eudat.eu/support-request

**Comment by bne86** [comment]
1. We are aware of the email, in the past we had to do this because of the JUELICH mailrelay.
This has changed for b2access, we will register a email at csc and use it then. 
2. Reply-to is not possible at a first glance.
3. I will adjust the template after the next vc, please set yourself a reminder.
