### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by goncaloGIT** [EUDAT-B2DROP/b2drop-theme#27]
Hello EUDAT community

Im having the following issue, nextcloud works fine , the problem is, when i apply b2-drop theme and restart the httpd, i only get a blank page.

![image](https://cloud.githubusercontent.com/assets/25826516/23747088/5a2900f6-04b6-11e7-8b32-ddc85750802d.png)

How can i troubleshoot this ? i already saw the httpd logs but , dint help much

![image](https://cloud.githubusercontent.com/assets/25826516/23747171/a4600a66-04b6-11e7-8b7b-14b0c918f35b.png)

Best regards

**Comment by apw1388** [comment]
Hi @goncaloGIT,
which Nextcloud version and which branch do you use?

**Comment by goncaloGIT** [comment]
Hello @apw1388 

First: l will like to thanks for your fast reply
Second: Heres some information about the enviroment
SO: CentOS 7
Nextcloud: 9.0.53
Branch: Master

Should i try the nexcloud branch ?

**Comment by apw1388** [comment]
@goncaloGIT we started theme adaption for Nextcloud 11 (branch nextcloud). Please test owncloud9 branch. It was developed with OwnCloud but Nextcloud 9 was quiet close to OwnCloud.

**Comment by goncaloGIT** [comment]
worked like a charm 👍 :D

But it seems to me that some images are broken, since for now im just doing a proof of concept, as it is, this works fine for me. But do  you recomend any version of nextcloud/owncloud + branch ? Wich one is working better ?

**Comment by bne86** [comment]
Hi,
on our development server (fsd-cloud48.zamk.fa-juelich.de) we are running theme:master and b2sharebridge:master. But on the production system (b2drop.eudat.eu) we are running nextcloud 11 with theme:nextcloud and b2sharebridge:nextcloud11
One problem that you could have: The theme is designed in a way that nextcloud is deployed to the docroot of your webserver, so the /nextcloud path could be a problem. We decided to implement it this way because we had some trouble with absolute/relative path's in the past

**Comment by goncaloGIT** [comment]
Hi @bne86 

Thanks for your elaborated post, it will definitely help me in the future.
Once again thank you for all your help and quick responses. 

Best regards
